<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.5.5.1 setup script
 * Date: Fri, 11 Mar 2016 04:14:43 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: Kartees [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'Kartees';
$cfg['Servers'][$i]['host'] = 'us-cdbr-iron-east-03.cleardb.net';
$cfg['Servers'][$i]['port'] = 3306;
$cfg['Servers'][$i]['socket'] = '3306';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['auth_type'] = 'config';
$cfg['Servers'][$i]['user'] = 'b3c48395bc1a72';
$cfg['Servers'][$i]['password'] = 'facf79d9';

/* End of servers configuration */

$cfg['blowfish_secret'] = '56e242b2560d68.59295682';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
?>